# Configurações do painel fotovoltaico e backend
# Gerado automaticamente se não existir.

[pv]
voc0 = 22.06
isc0 = 0.70
vmp0 = 18.81
imp0 = 0.63
alphav = -0.31        # [%/°C] - será dividido por 100 no código
alphai = 0.06         # [%/°C] - será dividido por 100 no código
G0 = 1000
T0 = 25
q = 1.602e-19
kConst = 1.3806503e-23
Ns = 36

[app]
PORT = 4000

DB_HOST = painel-mysql
DB_PORT = 3306
DB_USER = root
DB_PASS = RunicK137
DB_NAME = painelSolar

MQTT_URL = mqtt://cerise.freeddns.org:30001
MQTT_USER = infinitwin_user
MQTT_PASS = IwtLab#2025!
MQTT_PINS_TOPIC = /painelfotovoltaico.gerador/GPIO

AUTH_DIR = /data/baileys_auth_info
LOG_LEVEL = error

GPIO_THING_ID = painelfotovoltaico.gerador:GPIO
MQTT_ESTIMATED_POWER_TOPIC = /painelfotovoltaico.referencia/estimatedPower
MQTT_PV_CONFIG_CMD_TOPIC = /painelfotovoltaico.node/pvConfig
ESTIMATED_POWER_THING_ID = painelfotovoltaico.node:estimatedPower
MQTT_ALL_TOPIC = /painelfotovoltaico.node/all
ALL_THING_ID = painelfotovoltaico.node:all