services:
  painel-app:
    build: .
    container_name: painel-solar-app
    restart: unless-stopped
    ports:
      - "4000:3000"
    environment:
      PORT: 3000
      LOG_LEVEL: info
      DB_HOST: mysql
      DB_PORT: 3306
      DB_USER: root
      DB_PASS: RunicK137
      DB_NAME: painelSolar
      MQTT_URL: mqtt://cerise.freeddns.org:30001
      MQTT_PINS_TOPIC: /painelfotovoltaico.gerador/GPIO
      AUTH_DIR: /data/baileys_auth_info
    volumes:
      - baileys_auth:/data/baileys_auth_info
      - ./data:/data
      - ./public:/app/public
      - ./server-v2.js:/app/server-v2.js
      - ./config.ini:/app/config.ini
    depends_on:
      - mysql

  mysql:
    image: mysql:8.4
    container_name: painel-mysql
    environment:
      - MYSQL_ROOT_PASSWORD=RunicK137
      - MYSQL_DATABASE=painelSolar
    ports:
      - "3307:3306"
    volumes:
      - ./mysql-data:/var/lib/mysql

volumes:
  baileys_auth:
